### ISSUE TITLE
有没有相似度的计算

### ISSUE THREAD

**Issue by DavyLin** [xlturing/Simhash4J#1]
目前查看这边，只有一个是否相似的true/false，如果需要计算两篇文档，有什么方式改造吗？

**Comment by xlturing** [comment]
是指增加具体相似度？

**Comment by DavyLin** [comment]
是的，我有一个类似的需求 ，需要比对两篇文档（比如doc）的内容相似度，这块有没有什么可以借鉴的思路

**Comment by xlturing** [comment]
如果数据量很大，而且对实施性要求比较高，可以考虑simhash

**Comment by AndyNiu** [comment]
分段时候取余数有问题，应该是16，不应该是4。

**Comment by xlturing** [comment]
@AndyNiu hi andy，你是是指吧fracCount 改了吗？

**Comment by xlturing** [comment]
@AndyNiu hi andy，的确是bug，多谢提醒，我修复了
