### ISSUE TITLE
分段存储好像写错了，只保存了前16位

### ISSUE THREAD

**Issue by mingrenbuke** [xlturing/Simhash4J#2]

**Comment by xlturing** [comment]
hi，时间有点久了，能具体指出是代码第几行吗？

**Comment by mingrenbuke** [comment]
感觉store或者spliteSimhash有点问题，因为splitSimhash产生的是16*4的形式，而store函数第二行i<fracCount，则只保存了前4*4

**Comment by mingrenbuke** [comment]
是不是应该是List<String> lFrac = splitSimhash(simhash, 64／fracCount);

**Comment by xlturing** [comment]
hi，我看了下，是吧simhash出来的code分成了四段，所以只需要遍历四次

**Comment by mingrenbuke** [comment]
但你调用splitSimhash时，好像把64位的数据分成了16段，而不是4段

**Comment by xlturing** [comment]
hi，mingrenbuke，十分感谢提醒，的确是bug，我已经修复了
